version: '3.8'

services:
  pflink:
    image: local/pflink
    container_name: pflink
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8050
    volumes:
      - ./:/app/
    environment:
      PFLINK_MONGODB: mongodb://pflink-db:27017
      MONGO_USERNAME: admin
      MONGO_PASSWORD: admin
      LOG_LEVEL: INFO
      MAX_WORKERS: 24
    ports:
      - "8050:8050"
    networks:
      local:
      pflink:

  pflink-db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - type: volume
        source: MONGO_DATA
        target: /data/db
    restart: unless-stopped
    networks:
      pflink:

  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=pflink-db
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_AUTH_USERNAME=admin
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=admin
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
      - pflink-db
    ports:
      - "8888:8081"
    restart: unless-stopped
    networks:
      local:
      pflink:

networks:
  local:
  pflink:
  
volumes:
  MONGO_DATA:
