version: '3.8'

services:
  pflink:
    image: local/pflink
    container_name: pflink
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8050
    volumes:
      - ./:/app/
    environment:
      PFLINK_MONGODB: mongodb://pflink-db:27017
      MONGO_USERNAME: admin
      MONGO_PASSWORD: admin
      LOG_LEVEL: INFO
    ports:
      - "8050:8050"
    networks:
      local:
      pflink:

  pflink-db:
    image: mongo:4.4.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - type: volume
        source: MONGO_DATA
        target: /data/db
      - type: volume
        source: MONGO_CONFIG
        target: /data/configdb

    restart: unless-stopped
    networks:
      pflink:
    
networks:
  local:
  pflink:
  
volumes:
  MONGO_DATA:
  MONGO_CONFIG:
  
