version: '3.8'

services:
  pflink:
    image: local/pflink
    container_name: pflink
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8050
    volumes:
      - ./:/app/
    environment:
      PFLINK_MONGODB: mongodb://pflink-db:27017
    ports:
      - "8050:8050"
    networks:
      local:
      pflink:

  pflink-db:
    image: mongo:4.4.6
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 27017:27017
    volumes:
      - pflink-db-data:/data/db
    restart: unless-stopped
    networks:
      pflink:
    
networks:
  local:
  pflink:
  
volumes:
  pflink-db-data:
  
