version: '3.8'

services:
  mongodb:
    image : mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 27017:27017    
    volumes:
      - mongod:/data/db
    restart: unless-stopped
    
  pflink:
    image : local/pflink
    container_name : pflink
    volumes:
      - pflink:/home/pflink
    ports:
      - 8050:8050
  
volumes:
    mongod:
    pflink:

