version: '3.8'

services:
  pflink:
    image: fnndsc/pflink:20230302-minichris
    container_name: pflink
    restart: unless-stopped
    environment:
      PFLINK_MONGODB: mongodb://pflink-db:27017
      PFLINK_PFDCM: http://pfdcm:4005
      PFLINK_PORT: 4010
    ports:
      - "4010:4010"
    networks:
      local:
      pflink:


  pflink-db:
    image : mongo
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - pflink-db-data:/data/db
    restart: unless-stopped
    networks:
      pflink:
    
volumes:
    pflink-db-data:

networks:
    local:
    pflink:
