version: '3.8'

services:
  pflink:
    image : pflink
    container_name: pflink
    network_mode: host
  mongodb:
    image : mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 27017:27017    
    volumes:
      - /home/sandip/pflink/database:/data/db
    restart: unless-stopped
